### PR TITLE
Make tests pass on current Pharo 8

### LINKED ISSUE #7: Missing dependency: GTEventRecorderTestServer
This Transcript message shows it:
~~~
'EREventRecorderDelegateTest>>setUp (GTEventRecorderTestServer is Undeclared)'
'EREventRecorderPutHandlerTest>>setUpServer (GTEventRecorderTestServer is Undeclared)'
~~~
Loaded in a Pharo 8 downloaded today using:
~~~
Metacello new 
  baseline: 'EventRecorder'; 
  repository: 'github://pharo-contributions/EventRecorder/';
  load.
~~~

### PR DESCRIPTION
**Pull request by tinchodias**
Fixes #7 but includes more fixes.

Note I was just learning what EventRecorder is.

### CODE REVIEW

**Comment by Ducasse** [comment]
Thanks martin
Do you want to have commit access? I do not really want to maintain this package.

**Comment by tinchodias** [comment]
In fact, just After sound the fork and PR I realized that I have write access to push directly.

**Comment by Ducasse** [comment]
Oki
Thanks a lot martin. 
This package is important. 
But I do not have the energy or will to maintain it.

**Comment by tinchodias** [comment]
Do you consider everything in the sthub repository is migrated here or may be more important stuff?

**Pull request merged**
